### ISSUE TITLE
Dar estilo a las graficas

### ISSUE THREAD

**Issue by belramgut** [EGC-G2-Trabajo-1718/portal-votaciones#10]
Las gráficas se muestran correctamente y deben integrarse en el diseño web de la pagina del portal de votaciones, haciendo uso del estilo y colores que se han elegido

**Prioridad**: Baja
**Rama:** Visualización_resutados-estilo_web
**Estado**: COMPLETADO
**Subsistemas involucrados:** equipo de estilo (subequipo de visualización de resultados)

**Comment by adrluqmon2** [comment]
Una de las gráficas siguen sin tener la paleta de colores establecida. Aumentamos la prioridad de la petición debido a la cercanía de la fecha de entrega.

**Prioridad**: Alta
**Rama**: Visualización_resutados-estilo_web
**Estado**: PENDIENTE
**Subsistemas involucrados**: equipo de estilo (subequipo de visualización de resultados)

**Comment by emibelmar** [comment]
Se completa cambiando el estilo a las graficas de horas, edad y paises.

El commit se ha hecho en la rama de gráficas en lugar de la de estilo debido a una serie de problemas que han surgido para hacer uso del json-server tirando del codigo de la rama de estilo.
**Prioridad:** Alta
**Rama:** Visualización_resutados-graficas
**Estado**: Resuelto
**Subsistemas involucrados**: equipo de estilo (subequipo de visualización de resultados)
