### ISSUE TITLE
Simulación de datos recibidos

### ISSUE THREAD

**Issue by emibelmar** [EGC-G2-Trabajo-1718/portal-votaciones#11]
Se necesita simular los datos recibidos del subsistema de Recuento mediante algún tipo de servidor.
  
**Prioridad**: Alta
**Rama:** visualizacion_resultados_graficas
**Estado**: EN DESARROLLO
**Subsistemas involucrados:** equipo de visualización de resultados (subequipo de gráficas)

**Comment by belramgut** [comment]
La simulacion de datos se hará mediante una API creada en un json-server que se utilizará desde un contenedor docker incluido en la maquina virtual de desarrollo

**Comment by adrluqmon** [comment]
Dicha simulación ya puede encontrarse en el repositorio.
