### ISSUE TITLE
Creación de nueva vista

### ISSUE THREAD

**Issue by belramgut** [EGC-G2-Trabajo-1718/portal-votaciones#12]
Se ha creado una nueva gráfica que representa los votos por países.
Se necesita que se integre en la aplicación en una nueva vista.
  
**Prioridad**: Moderada
**Rama:** Visualización_resutados-estilo_web
**Estado**: Completada
**Subsistemas involucrados:** equipo de estilo (subequipo de visualización de resultados)

**Comment by dierodfer** [comment]
se debe de esperar a hacer ''merged'' a la rama dev-visualizacion ya que no tenemos disponible dicha gráfica en nuestra rama

**Comment by adrluqmon2** [comment]
Se ha realizado ya el merged? Si no es así, notificanos cuando este, para probar que funcione correctamente.

**Comment by dierodfer** [comment]
se acaba de realizar el merged en unas horas se realizará la petición

**Comment by dierodfer** [comment]
Tarea realizada por @adrluqmon en el commit 9a3d9a60fd99a5bdb70773167ae981f9bff22009
