### ISSUE TITLE
Cambio de estructura de datos recibidos

### ISSUE THREAD

**Issue by dierodfer** [EGC-G2-Trabajo-1718/portal-votaciones#13]
Datos recibidos por el subsistema de recuento han sido modificados, se necesita reestructurar el parseo de los objetos recibidos de nuevo.

Los detalles en la wiki de recuento:
[https://1984.lsi.us.es/wiki-egc/index.php/Recuento_de_votos_-_17_18_-_G2](url)

**Prioridad**: Alta
**Rama:** visualizacion_resutados_graficas
**Estado**: COMPLETADO
**Subsistemas involucrados:** equipo de graficas (subequipo de visualización de resultados)

**Comment by belramgut** [comment]
Se han efectuado los cambios en el commit 22944f6309c912e1da7311cb48916ac226883ba8
