### ISSUE TITLE
Creación de nueva gráfica edad Prueba

### ISSUE THREAD

**Issue by dierodfer** [EGC-G2-Trabajo-1718/portal-votaciones#20]
-se pide que la nueva gráfica tenga un rango de 5 en 5 años
-se pide que se represente en una vista nueva y sea diferente a las otras ya creadas
-estructura horizontal y representarlas mas de una gráfica en una vista

**Prioridad**: Alta
**Rama:** visualizacion_resultados_graficas y visualización_resultados-estilo_web
**Estado**: PENDIENTE
**Subsistemas involucrados:** visualización de resultados

**Comment by belramgut** [comment]
El parseo de la grafica está realizado  7f8de7ee453ec9d5901f08c9c9d2619dbddb0e70

**Comment by davsotsan** [comment]
Nueva vista realizada para las gráficas
