### ISSUE TITLE
Modificación de propiedades gráficas

### ISSUE THREAD

**Issue by dierodfer** [EGC-G2-Trabajo-1718/portal-votaciones#8]
Se pide al subequipo de gráficas las siguientes modificaciones en las gráficas: 

**Gráfica resultados:**
1. - [ ] Mostrar el porcentaje de cada opción
2. - [x] Resaltar opción ganadora

**Gráfica censo:**

3. - [ ] Mostrar porcentaje 
4. - [ ] Ocultar/eliminar grill 

	   

**Prioridad**: Baja
**Rama:** visualizacion_resultados_graficas
**Estado**: EN DESARROLLO
**Subsistemas involucrados:** equipo de visualización de resultados (subequipo de gráficas)

**Comment by belramgut** [comment]
El porcentaje de cada opción sólo es posible mostrarlo haciendo uso de una librería javascript auxiliar a chartjs que habría que incluir en el proyecto.
La opción ganadora se resalta en otro color, mientras que las otras opciones aparecen en el mismo color aleatorio.
El grill no tiene opción de ser desactivado usando la librería actual
