### ISSUE TITLE
Estilado de listas

### ISSUE THREAD

**Issue by dierodfer** [EGC-G2-Trabajo-1718/portal-votaciones#9]
Las vista de listas tienen una versión inicial se deben mejorar su visualización mas agradable sin dejar de ser responsive.

**Prioridad**: Baja
**Rama:** Visualización_resutados-estilo_web
**Estado**: Finalizado
**Subsistemas involucrados:** equipo de estilo (subequipo de visualización de resultados)

**Comment by emibelmar** [comment]
Se termina la tarea y se procede a subir los cambios al repositorio
